Footjob Arachne (10049)(WIP)
OfficialLayton/Succubus-Duel-English-Translation pull request #23
Opened 2024-02-07 21:51 UTC by PummelsTL

Placeholder for Footjob Arachne.
Changing (WIP) -> (Ready) after everything in the file is translated. Keep the pull request open until then.

2024-03-12 05:44 UTC, OfficialLayton commented
I reviewed and updated your translation for the Footjob Arachne today! Super duper well done! 

Iroji has added a new English folder for purely translations, which should make translating easier. I have taken the liberty to transfer your exisiting translation over, as well as clean up any errors I found like spelling, mistakeningly placed ",", and minor changes. Looks really good, and you've translated the entire character! Overall I have very little complaints, and I think you translated the character in a reasonably natural way ^^

2024-03-14 07:59 UTC, PummelsTL commented
I'm done with the final changes. The pull request can be merged if nothing looks wrong.

2024-03-15 07:23 UTC, OfficialLayton requested changes
Some real good proofreading additions @PummelsTL! Really nice work!
I had some comments here and there I'd love to get your opinon on. Looking forward to hearing from you! ^^

2024-03-15 07:23 UTC, OfficialLayton commented on CSV/Language/English/Card/10049.txt
> +ほらほらぁ、あん❤あん❤っていいながら\n腰を上下にふってあげる❤\n騎乗位のまねだよー❤,Look here❤ I'll move my hips up and down while moaning❤ Ah❤ Ah❤ I'll pretend that I'm riding your dick❤
Hmm, I don't know I think "Look here" as a sentence doesn't quite fit. Maybe something like "Look at this" could be more fitting?

2024-03-15 07:23 UTC, OfficialLayton commented on CSV/Language/English/Card/10049.txt
> +マゾってきもーい❤くすくす❤,You masochists are so gross❤ Kuhuhu❤
For the translation of くすくす, I think it's more of a subtile laugh rather than a boastful one like "Ahaha", if not Kuhuhu, maybe something like *giggle*? What do you think?

2024-03-15 07:23 UTC, OfficialLayton commented on CSV/Language/English/Card/10049.txt
> -おちんちんに脳みそ支配されちゃって、さすが男って感じ。\nくすくす❤さっさと精液搾り取ってあげるよ❤,It was stupid to expect anything more❤ Men always think with their dicks❤ Ahahaha!❤ I'll start squeezing out your semen right away❤
"Ahaha" definitely works as a translation here better than kuhuhu I must admit ^^

2024-03-15 07:23 UTC, OfficialLayton commented on CSV/Language/English/Card/10049.txt
> +ほらほらほら❤お兄ちゃんの雑魚おちんちんなんて、\nわたしの足さばきでかるーくイかせてあげる❤\nおちんちんを両側からしこしこされて気持ちいいねー❤きゃはは❤,Here! It'll be easy for me to make you cum with my foot skills❤ It feels good when I rub your dick from both sides; rig
I don't really think the word "here!" Really does anything to translate ほらほらほら. If not hora hora hora, then maybe something like, "take this and this and this!"?

2024-03-15 07:23 UTC, OfficialLayton commented on CSV/Language/English/Card/10049.txt
> +腰が浮いてきて気持ちよくなっちゃうよねー❤\nタマタマばっかりグニグニされて頭まっしろ❤\nほら、イケ❤イケ❤ザーコ❤,It's feeling so good that your hips are shooting forward❤ Just let your mind go blank while I play with your balls❤ C'mon; do it❤ Cum❤ You
Assuming she's talking about balls in the previous line, maybe "they're feeling so good" is better than "It's feeling so good"... what do you think?

2024-03-15 14:47 UTC, PummelsTL commented on CSV/Language/English/Card/10049.txt
> +腰が浮いてきて気持ちよくなっちゃうよねー❤\nタマタマばっかりグニグニされて頭まっしろ❤\nほら、イケ❤イケ❤ザーコ❤,It's feeling so good that your hips are shooting forward❤ Just let your mind go blank while I play with your balls❤ C'mon; do it❤ Cum❤ You
I'm fairly sure Yatsume is also continuing the footjob here, not just the ball fondling. I changed it to: "Your hips are shooting forward with how good it feels."

2024-03-15 14:49 UTC, PummelsTL commented on CSV/Language/English/Card/10049.txt
> +ほらほらほら❤お兄ちゃんの雑魚おちんちんなんて、\nわたしの足さばきでかるーくイかせてあげる❤\nおちんちんを両側からしこしこされて気持ちいいねー❤きゃはは❤,Here! It'll be easy for me to make you cum with my foot skills❤ It feels good when I rub your dick from both sides; rig
Changed to "Take this, and that!". My view on using "hora" is that it's not proper English.

2024-03-15 15:00 UTC, PummelsTL commented on CSV/Language/English/Card/10049.txt
> +マゾってきもーい❤くすくす❤,You masochists are so gross❤ Kuhuhu❤
I think it works as is. I'd rather use onomatopoeia than descriptive words like *giggle* in dialogue.

2024-03-15 15:01 UTC, PummelsTL commented on CSV/Language/English/Card/10049.txt
> +ほらほらぁ、あん❤あん❤っていいながら\n腰を上下にふってあげる❤\n騎乗位のまねだよー❤,Look here❤ I'll move my hips up and down while moaning❤ Ah❤ Ah❤ I'll pretend that I'm riding your dick❤
Changed to "Look at this."

2024-03-17 02:42 UTC, OfficialLayton commented on CSV/Language/English/Card/10049.txt
> +腰が浮いてきて気持ちよくなっちゃうよねー❤\nタマタマばっかりグニグニされて頭まっしろ❤\nほら、イケ❤イケ❤ザーコ❤,It's feeling so good that your hips are shooting forward❤ Just let your mind go blank while I play with your balls❤ C'mon; do it❤ Cum❤ You
Ahh it might be a line for a different attack line then. That would make sense ^^

2024-03-17 02:44 UTC, OfficialLayton commented on CSV/Language/English/Card/10049.txt
> +マゾってきもーい❤くすくす❤,You masochists are so gross❤ Kuhuhu❤
Hmm I'm not sure, especially since the character has already said あはは, which was translated to "Ahaha". I don't think *Giggle* is non-standard so something like that might be better...

2024-03-17 02:45 UTC, OfficialLayton commented on CSV/Language/English/Card/10049.txt
> +あはは❤バカにされているのにズボン膨らましているし❤\nおちんちんイライラしちゃったねー❤\n足で踏んであげるから、たっぷり喘いでね❤マーゾ❤,Ahaha❤ I made fun of you; and your pants started bulging❤ Your dick must be pissed off❤ I'll trample it; so make sure to moan h
I think since あはは is being translated to Ahaha, I think くすくす should either be "Kuhuhu" or *Giggle*. What do you think?

2024-03-17 04:27 UTC, merged