Merchant's daugther at the arena
OfficialLayton/Succubus-Duel-English-Translation pull request #5
Opened 2024-02-04 13:56 UTC by PummelsTL

-Initial encounter up to choices
-Last Encounter

2024-02-04 21:41 UTC, Fyurios commented on CSV/Card/80019.txt
> +        説明,After saying that, the girl grabbed my hand into her own. It certainly felt like her hand was warmer normal.
Warmer than normal would sound better here.

2024-02-04 21:42 UTC, Fyurios commented on CSV/Card/80019.txt
> +        セリフ,（Uuuh❤ Why... I'm feeling weak for some reason❤）
Why... am I feeling weak        The for some reason here is implied with the why, I wanna say it isn't needed.

2024-02-04 21:43 UTC, Fyurios commented on CSV/Card/80019.txt
> +        セリフ,Really?\nAhaha❤ This is amazing❤ Even cardmasters can't falling for my charm❤
Even cardmasters can't falling for my charm    Sounds a bit off. I'd say
Even card masters fall for my charms

2024-02-04 21:44 UTC, Fyurios commented on CSV/Card/80019.txt
> +        セリフ,Hey, Oniisan. Why don't we go over to that corner?\nThere aren't many people there, so we can play by just the two of us❤
play by   - play with

2024-02-04 21:44 UTC, Fyurios commented on CSV/Card/80019.txt
> +        説明,The girl started to gently pull me over to a blindspot at the corner of the room. In that situation, I...
blind spot is normally 2 words instead of one.

2024-02-04 21:45 UTC, Fyurios commented on CSV/Card/80019.txt
> +            説明,While saying that, the girl showily rubbed her hands together in front of you. Seeing that, you couldn't help recalling how soft and amazing her hands felt just now, which made you wan
the girl showily rubbed her hands together 

I want to say showily doesn't fit there due to grammar rules. Would probably be best to remove it.

2024-02-04 21:46 UTC, Fyurios commented on CSV/Card/80019.txt
> +            説明,However, I held my ground and pulled back from the girl back to the counter. Even when she was just a small girl, you felt a sense of danger for some reason and felt like you shouldn't
You changed perspective here. You probably should make it first person like the rest of the descriptions.

Even when she    when doesn't fit here.

Even though she

2024-02-04 21:47 UTC, Fyurios commented on CSV/Card/80019.txt
> +        説明,Just by hands with her, your palm felt warm and you could feel a pleasant sensation flowing into you.
Just by hands
I think you forgot a word here
Just by holding hands

2024-02-04 21:47 UTC, Fyurios commented on CSV/Card/80019.txt
> +        セリフ,（Uuh❤ I'm losing the strenght in my body...❤ It feels good...❤)
strenght 

strength

2024-02-04 21:47 UTC, Fyurios commented on CSV/Card/80019.txt
> +        説明,When the girl saw my dreamy state, she gave me a wide smile and, furthermore, intertwined fingers with me like a lover.
fingers

her fingers

2024-02-04 21:48 UTC, Fyurios commented on CSV/Card/80019.txt
> +        説明,She slid her fingers between mine and gently squeezed. Just by doing that, she made my whole body relax as if directly massaging my mind and put me into a trance.
Just by doing that, she made my whole body relax as if directly massaging my mind and put me into a trance.

Grammar here seems off. Perhaps something more like

That was all it took to put me in a trance, my body relaxing as if she were directly massaging my mind.

2024-02-04 21:51 UTC, Fyurios requested changes
Looks good overall. As I mentioned in a dm, we can't use normal commas so feel free to replace them with 、    、     、    、
I posted a few comments about some grammar stuff if you wanted to make some quick changes.

2024-02-06 11:10 UTC, PummelsTL commented
Keep this open until I've finished translating all the scenes in the file.

2024-02-07 21:45 UTC, PummelsTL commented
The file is fully translated and ready for last review.

2024-02-08 05:07 UTC, Fyurios requested changes
Just saw a few grammar things off, mostly the same line in different sections.

2024-02-08 05:07 UTC, Fyurios commented on CSV/Card/80019.txt
> +    &フレーバーテキスト,Peddler's daugther who loves her father. She has been feeling lonely after her father suddenly stopped playing with her after peddling to a faraway village. This led to her taking away
A peddler's daughter

2024-02-08 05:07 UTC, Fyurios commented on CSV/Card/80019.txt
> +        説明,When I returned her gaze out of curiousity; she beckoned me over; so I decided to see what she has to say.
curiosity

2024-02-08 05:07 UTC, Fyurios commented on CSV/Card/80019.txt
> +        説明,After that; I "played" with the girl until the night. Even when I had dirtied my pants; she only needed to give them a touch with her hand to absorb and clean off all the semen from them.
until late at night would probably sound better.

2024-02-08 05:07 UTC, Fyurios commented on CSV/Card/80019.txt
> +        説明,After that; I "played" with the girl until the night. Even when I had dirtied my pants; she only needed to give them a touch with her hand to absorb and clean off all the semen from them.
until late at night would probably sound better.

2024-02-08 05:07 UTC, Fyurios commented on CSV/Card/80019.txt
> +        説明,After that; I "played" with the girl until the night. Even when I had dirtied my pants; she only needed to give them a touch with her hand to absorb and clean off all the semen from them.
until late at night would probably sound better.

2024-02-10 23:31 UTC, PummelsTL commented
Added the grammar fixes.

2024-02-12 22:10 UTC, merged